name: Generate Streak Card

on:
  schedule:
    - cron: "0 */12 * * *"
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  generate:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: Generate streak.svg
        uses: ashutosh00710/github-readme-streak-stats@main
        with:
          account: ${{ github.repository_owner }}
          extension: svg
          theme: tokyonight
          hide_border: true
          background: 10141E
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Push streak.svg to output branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: streak-output
          build_dir: .
          filename: streak.svg
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
